spring:
  application:
    name: appointment-service
  retry:
    maxAttempts: 3
    backoff:
      delay: 2000

google:
  calendar:
    credentials: src/main/resources/calendar-api.json
    application-name: Appointment Service

server:
  port: 8083


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
